### ISSUE TITLE
Grayscale with window-shader-fg?

### ISSUE THREAD

**Issue by matthewlscarlson** [yshui/compton#1020]
Because grayscale is easier on the eyes, I have a script which is supposed to toggle the system color on and off. The method I implemented is the one on ArchWiki (https://wiki.archlinux.org/title/picom#Grayscale), with the only difference being that I just put the code, all in one line, into a variable instead of a separate file. It was working until very recently. Now I am getting an error:

[ 02/04/2023 18:44:37.934 get_cfg WARN ] --glx-fshader-win has been replaced by "--window-shader-fg" for the new backends.

So --glx-fshader-win has obviously been replaced by --window-shader-fg. I looked at the 'Shader Interface' part of the documentation (https://github.com/yshui/picom/blob/next/man/picom.1.asciidoc#shader-interface), but, because I am not familiar with OpenGL (let alone custom shaders), the new method isn't at all clear to me.

Can the new code be used in a one-liner like before? How would I go about accomplishing this? I want to put it into my script instead of messing around with configuration files.

Thanks!

**Comment by absolutelynothelix** [comment]
> It was working until very recently. Now I am getting an error:
> ```
> [ 02/04/2023 18:44:37.934 get_cfg WARN ] --glx-fshader-win has been replaced by "--window-shader-fg" for the new backends.
> ```

it's because the backends previously known as experimental are default now. you can still access the old backends, now known as legacy, by using the `--legacy-backends` command line argument, but keep in mind that they may be completely removed one day.

that was a quick solution. if you want to figure out the new shader interface, the `--window-shader-fg` option accepts a path to a fragment shader, so you have to use it as `--window-shader-fg=/path/to/a/fragment/shader.glsl` (the `.glsl` suffix is optional).

also, the new shader interface is different from the old one, so most likely your shader won't work without minor modifications. we're supposed to have an [example](https://github.com/yshui/picom/wiki/Shader-Shop#grayscale-filter) of a grayscale shader for the new shader interface, but it's a bit outdated (@yshui, update the shader!) and requires minor modifications as well. let me update it for you:
```glsl
#version 330

in vec2 texcoord;
uniform sampler2D tex;
uniform float opacity;

vec4 default_post_processing(vec4 c);

vec4 window_shader() {
	vec2 texsize = textureSize(tex, 0);
	vec4 color = texture2D(tex, texcoord / texsize, 0);

	color = vec4(vec3(0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b) * opacity, color.a * opacity);

	return default_post_processing(color);
}
```
it should work (i just can't test it right now), but if it won't feel free to report back, or you could fix it on your own looking at the log messages that'll tell you what's wrong with the shader you're trying to use.

**Comment by matthewlscarlson** [comment]
Thank you for the useful comment. The code is nearly perfect: You accidently put a bracket after the first 'opacity' on line 13. ;-)

Both methods work, but I'll go ahead and use the new shader interface because (as you said) the '--legacy-backends' option could be removed at any time.

I am marking this as closed.
