### ISSUE TITLE
Clashes with existing composite manager

### ISSUE THREAD

**Issue by tsipinakis** [yshui/compton#1104]
Hi,

I am the Debian maintainer of picom, opening this to forward bug [#1040988](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040988)

> picom adds an autostart file which makes it automatically start on
session login.
> Today I noticed that journald/rsyslog ran while and my logs were flodded
with the following messages (I was logged into a GNOME session at that
time):
> Jul 13 19:18:11 pluto picom.desktop[2236]: [ 13.07.2023 19:18:11.510 redirect_start FATAL ERROR ] Another composite manager is already running (and does not handle _NET_WM_CM_Sn correctly)
> Jul 13 19:18:11 pluto picom.desktop[2236]: [ 13.07.2023 19:18:11.510 redirect_start FATAL ERROR ] Another composite manager is already running (and does not handle _NET_WM_CM_Sn correctly)
> Jul 13 19:18:11 pluto picom.desktop[2236]: [ 13.07.2023 19:18:11.510 redirect_start FATAL ERROR ] Another composite manager is already running (and does not handle _NET_WM_CM_Sn correctly)
> Within minutes, my disk was filled with hundreds of megabytes of log
data (/var/log/syslog was over 1GB), before I killed the rogue picom
process.

It looks like picom does not like if it is auto-started along another composite manager (i.e. GNOMEs). It should gracefully exit and not cause an infinite loop, filling up the log files in the process.

### Platform
Debian sid

### Environment
GNOME (and others?)

### picom version

10.2

### Steps of reproduction

1. Install picom
2. Log into a GNOME session

**Comment by absolutelynothelix** [comment]
i don't think that we've changed anything related to this but it still would be good to test picom built from the latest commit in the next branch as there was a lot of changes since v10.2.

i think that both gnome's compositing manager and picom are guilty. gnome's compositing manager is guilty for not following the manager selections specification (for example, picom exits with "Another compositing manager is already running" when started alongside xfce's compositing manager) and picom is guilty for not exiting after this error. i think the fix will be to simply exit after this error.

cc @yshui

**Comment by Soblow** [comment]
Hello,
Since mid-august, `picom` has been removed from Debian testing repositories marking this issue as blocking for reintroduction.
Are there any updates about this?
Thanks in advance!
