### ISSUE TITLE
[Feature Request] Adding animations

### ISSUE THREAD

**Issue by r0-zero** [yshui/compton#911]
Hello,

I just want to ask a quick question about animations. I have succesfully implemented animations and fully upstreamed to yshui picom/next . However, I made this for phyOS (dwm) only and with a few tweaks I can probably get all the animations to work on any window manager. 

It supports more than 10 unique animations (including open/close window also fading in/out when switching workspaces). I did not make a pull request now because it is limited to pdwm. My question is, if you have time, could you please check the fork, and if you seem it is okay, I will change the source code to fit any window manager. 

Also as a side note, 
No drawing delay in rounded corners
No errors when resizing because it will generate events to setting window flags (works like it is only resized once)
No performance issues with shadows
No bugs in interpolation or resizing transparent windows
No flickering

I would be glad if you can check it. Normally I did not think about making this to fit all window managers, but I got lots of request, so I think if you are okay I can give it a go.

https://github.com/yshui/picom/compare/next...FT-Labs:picom:next

**Comment by yshui** [comment]
Is your change based on #772 ? Can you coordinate with @dccsillag? Do you want to take over that PR?

**Comment by r0-zero** [comment]
Yeap it is. Sure! If you are okay with it.

**Comment by yshui** [comment]
I am not the one who needs to be okay with it :slightly_smiling_face: 

@dccsillag, I am sure you are busy but can you have a look?

**Comment by dccsillag** [comment]
Yup, sure can.

I took a quick look (https://github.com/dccsillag/picom/compare/implement-window-animations...FT-Labs:picom:next), it looks like there are just 10 commits (none of which is particularly massive) other than work on yshui/picom. @FT-Labs, does this sound right, or am I not understanding Github's UI?

Also, it would be nice if you could point out more or less what makes it exclusive to pdwm. I couldn't quite see it from my quick glance (I'll look at it more carefully later today).

I feel like there are a few details that might need some work in the code (particularly regarding the bit with window resizing and `animation_progress != 1` checks), but again, I need to look at it a bit more carefully. I also *think* there are some open issues in my repo that will still need to be solved before finally merging into yshui/picom (e.g., pixmap blending with application opacity), but this would be nice progress nontheless.

@FT-Labs, if we are to take a go at this, could you open a PR in my repo? (Suggestion: create a separate branch in your repo so that our work on this doesn't interfere with your old work.)

**Comment by r0-zero** [comment]
@dccsillag 

I will clean the commit history if you guys seem okay with it, shadow issues have bugged me so I made some unnecessary commits.
About that animation progress, the issue is that whenever a window is resized (if you check picom logs) or destroyed, since the window is destroyed but animation is still going on, it will pop up lots of errors that window flags cleared and reset. There should be a better way to handle that, but whenever those things happen (each resize) picom will clear its flags / release shadows and rebind them again, which causes enormous laggy animation with enormously slow performance.

As for the commit, I've cleaned up old commits to be able to merge it with yshui/next, you should be checking this one for it:
https://github.com/yshui/picom/commit/f6b0b04f5bd8bc5f727cc3bb17802a88ca87ed51

pixmap blending with application opacity as for this one, I've solved this with focusing issues and using a rule for transparent applications in configuration, but there is probably a better way to handle this issue.

As for pdwm, the issue is most of the other window managers unmap/map windows on desktop changes. However in pdwm, there is no full ewmh support and windows are never unmapped (only if a patch included to hide some applications), they are always moved above to y=0 position of root window (3/2 * window height). Which is why I never used ewmh atoms to handle this problem, only checked animation position destination of window, if it's pending y position is above the monitor by some margin, it means that that window is leaving the current workspace, and if window's current g.y is above the monitor and pending_g.y is >0 + some margin then it is entering the current workspace.

I will make a PR for it soon, thanks. I'd be glad if you can help me find a better way to solve blending issue, rather than using focused window to manage, it would be much better to handle it with openGL.

Also as a side note, lerping is not done in legacy backends, which makes animations look bad, I can implement them for older backends too.

**Comment by r0-zero** [comment]
```		
             if (is_animating && w->old_win_image) {
				bool is_focused = win_is_focused_raw(ps, w);
				if (!is_focused && w->focused && w->opacity_is_set)
					is_focused = true;
				assert(w->old_win_image);

				bool resizing =
					w->g.width != w->pending_g.width ||
					w->g.height != w->pending_g.height;

				// Only animate opacity here if we are resizing
				// a transparent window
				process_window_for_painting(ps, w, w->win_image,
								is_focused ? 1.0 : w->opacity >= 1 ? 1.0 : w->animation_progress,
								&reg_bound, &reg_visible,
								&reg_paint, &reg_paint_in_bound);

				// Only do this if size changes as otherwise moving
				// transparent windows will flicker and if you just
				// move so slightly they will keep flickering
				if (resizing && (!is_focused || !w->opacity_is_set)) {
					process_window_for_painting(ps, w, w->old_win_image,
									1.0 - w->animation_progress,
									&reg_bound, &reg_visible,
									&reg_paint, &reg_paint_in_bound);
				}
```

This is the temporary solution for alpha blending with transparent applications. Also handles flashing issue when spawning new windows.

**Comment by dccsillag** [comment]
> I will clean the commit history if you guys seem okay with it, [...]

Go for it! :smile: 

> About that animation progress [...]

Oh yeah, I'm all for checking the `animation_progress` value for stuff like that. What I meant, though, is that checking if it's `!= -1` or `== -1` is generally bad because it's a floating point number, and it can get really close to -1 (e.g., 10^-7, perhaps?) for a while before it actually gets to -1. It's better to check `abs(w->animation_progress - (-1)) <= EPS` (for some `EPS`, say 10^-7) or similar.

> I will make a PR for it soon, thanks. I'd be glad if you can help me find a better way to solve blending issue, rather than using focused window to manage, it would be much better to handle it with openGL.

re. blending: My conclusion in the past was that to solve it "properly" (i.e., lerping between the old pixmap and the new pixmap, including the alpha channel) would require writing a custom shader, which might be a bit of a rough change for picom. My plan was to provide some config option that would make it so that instead just the new pixmap is shown, but resized to the animated window size (if that's not something you've already implemented?). I personally think that looks even a bit better than the lerping, but I know other people differ. I can revisit the lerping idea, though.

> Also as a side note, lerping is not done in legacy backends, which makes animations look bad, I can implement them for older backends too.

I thought we were on the track to deprecating the legacy backends? That's why I didn't bother to implement that for them (also, that code is a tad messier).

**Comment by r0-zero** [comment]
All right, I'll handle those. If you can mark where needs to be fixed/what needs to be done, I'll be glad to implement your ideas. Thanks!

**Comment by dccsillag** [comment]
Of course :)

I think having a PR would be great for that, because then I can just leave the comments inline with the code and you can respond to them directly. So (unless you want to try some other scheme?) once we have a PR (no rush) I'll start adding comments to specific pieces of code about stuff like that.

**Comment by r0-zero** [comment]
Of course, I'll send a PR when I handle that ewmh atoms and remove pdwm specific code. 

By the way, there is a small issue on multi monitor setups:
For example on desktop switching animation, I have added minimize and maximize for it. (Minimized windows go from edges to center, incoming desktop goes from center to edges of the screen), however to handle it I wrote an atom in pdwm to fetch current monitor center position, because picom only uses root viewport, which is total pixels of all screens. Have you got any idea so that we can get the center point of current monitor? We could probably use some Xinerama (XineramaQueryScreens) function, but it could be great if there is some other way to handle that.

**Comment by raven2cz** [comment]
I will now speak for a lot of users on awesomewm, that we are **very** happy that the animations have finally been successfully added to the original picom. Fingers crossed!

I would like to ask about one of the critical points of the implementation. Will the animations be disabled when manually move and resize the window? I.e. in floating layout / floating window will the animations be turned off for move and resize windows? The biggest problem of all picom forks is the impossibility of turning off animations during normal/manual scrolling and resizing windows.
